###
GET http://localhost:3001/info 


### POSTs
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
  "name": "hawana",
  "number": "123-12322"
}


### POST
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
  "name": "hao",
  "number": "123"
}

### all
GET http://localhost:3001/api/persons 


###
GET http://localhost:3001/api/persons/1 


### 404
GET http://localhost:3001/api/persons/999 

###
PUT http://localhost:3001/api/persons/686203cbd5ec537c9fe38fef
Content-Type: application/json

{
  "name": "hao",
  "number": "12123"
}


### delete 404
DELETE http://localhost:3001/api/persons/kh


### delete 204
DELETE http://localhost:3001/api/persons/6860b68823efc3bc28682ec0


